//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsac
{
    using System;
    using System.Collections.Generic;
    
    public partial class общий_поставка
    {
        public int номер_поставки { get; set; }
        public Nullable<int> код_товара { get; set; }
        public string тип { get; set; }
        public string название { get; set; }
        public Nullable<int> id_поставщика { get; set; }
        public string название_поставщика { get; set; }
    }
}
