//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsac
{
    using System;
    using System.Collections.Generic;
    
    public partial class общий_заказ
    {
        public int код_заказа { get; set; }
        public Nullable<int> код_клиента { get; set; }
        public string фамилия { get; set; }
        public string имя { get; set; }
        public string отчество { get; set; }
        public string телефон { get; set; }
        public Nullable<System.DateTime> дата_заказа { get; set; }
        public string место_доставки { get; set; }
    }
}
