//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsac
{
    using System;
    using System.Collections.Generic;
    
    public partial class отсток_на_складе
    {
        public int код_товара { get; set; }
        public string тип { get; set; }
        public string название { get; set; }
        public string характеристика { get; set; }
        public string изготовитель { get; set; }
        public Nullable<decimal> цена { get; set; }
        public Nullable<double> остаток_на_складе { get; set; }
    }
}
