//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsac
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class поставка
    {
        [Key]
        public int номер_поставки { get; set; } //номер_поставки
        public Nullable<int> количество { get; set; }
        public Nullable<int> код_товара { get; set; }
        public Nullable<int> id_поставщика { get; set; }
        public Nullable<System.DateTime> дата_поставки { get; set; }
        public Nullable<decimal> сумма_поставки { get; set; }
    
        public virtual поставщик поставщик { get; set; }
        public virtual товар товар { get; set; }
    }
}
